apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: test
  labels:
    testsecret: 4lf0m
    envconfigtest: 0b1d8
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        envFrom:
        - configMapRef:
            name: envconfigtest-0b1d8
        volumeMounts:
        - mountPath: /test
          name: test-secret
      volumes:
      - name: test-secret
        secret:
          secretName: testsecret-4lf0m
